services:
  server:
    build:
      context: matchmaking/server
      target: builder
    stop_signal: SIGINT
    hostname: server
    user: "${RUNNER_UID}:${RUNNER_GID}"
    ports:
      - '8000:8000'
    volumes:
      - './logs:/server/tests/logs'

  solution:
    build:
      context: matchmaking/solution
    environment:
      SERVER_NAME: server:8000
    stop_signal: SIGINT