services:
  server:
    build:
      context: matchmaking/server
      target: builder
    stop_signal: SIGINT
#    hostname: server
    ports:
      - '8000:8000'
    volumes:
      - './logs:/matchmaking/server/tests/logs'

  solution:
    build:
      context: matchmaking/solution
    stop_signal: SIGINT